name: CI -> Deploy to My website
on:
  push:
    branches: 
      - staging
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Here is the deployment action
      - name: Use Node.js 14
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: 🔨 Build Project
        run: |
          npm install
          npm run build
      - name: List output files
        run: find build/ -print
      - name: Upload from public_html via FTP
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ftp.cherishlogistics.com
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_dir: "build/"
<<<<<<< HEAD
          remote_dir: "/public_html/staging.cherishlogistics.com/public_html/"
=======
          remote_dir: "/public_html/staging.cherishlogistics.com"
>>>>>>> staging
          delete: "false"